/**
 * Maps AI generated questions to the backend Question schema.
 *
 * @param {Object} aiQuestion - The question object generated by the AI
 * @param {Object} config - The configuration object used to generate the question
 * @returns {Object} - The mapped question object ready to be sent to the backend API
 */

/**
 * Normalises the difficulty value coming from the UI form into the
 * exact enum value expected by the Mongoose schemas.
 *
 * UI values  : 'easy' | 'medium' | 'hard'
 * Schema enum: 'easy' | 'moderate' | 'difficult'
 */
const normalizeDifficulty = (uiValue) => {
  switch (uiValue) {
    case 'easy':     return 'easy';
    case 'medium':   return 'moderate';
    case 'hard':     return 'difficult';
    // Pass through if already canonical (e.g. 'moderate', 'difficult')
    case 'moderate': return 'moderate';
    case 'difficult': return 'difficult';
    default:         return 'moderate'; // safe fallback
  }
};

export const mapAIToQuestionSchema = (aiQuestion, config) => {
  const difficulty = normalizeDifficulty(config.difficulty);

  if (config.type === 'mcq') {
    return {
      subject: config.subject,
      difficulty,
      question: aiQuestion.questionText,
      options: aiQuestion.options,
      correctAnswerIndex: aiQuestion.correctAnswerIndex,
      marks: parseInt(config.marksPerQuestion, 10) || 1,
      negativeMarks: 0,
      topic: config.topic,
    };
  }

  if (config.type === 'coding') {
    return {
      subject: config.subject,
      difficulty,
      title: `Coding Challenge: ${config.topic}`,
      description: aiQuestion.problemStatement,
      testCases: (aiQuestion.testCases || []).map((tc, index) => ({
        input: tc.input,
        expectedOutput: tc.expectedOutput,
        // Respect AI-provided isSample flag; otherwise mark the first test case
        // as the sample so students can use "Run Code" in the exam sandbox.
        isSample: tc.isSample === true || index === 0,
      })),
      templates: [
        {
          language: config.language || 'javascript',
          starterCode: aiQuestion.boilerplate || '',
        },
      ],
      marks: parseInt(config.marksPerQuestion, 10) || 5,
    };
  }

  if (config.type === 'theory') {
    return {
      subject: config.subject,
      question: aiQuestion.questionText,
      suggestedAnswer: aiQuestion.gradingRubric || '',
      maxMarks: parseInt(config.marksPerQuestion, 10) || 5,
      // New optional fields — supported by updated TheoryQuestion schema
      difficulty,
      topic: config.topic || '',
    };
  }

  return aiQuestion; // Fallback
};

