services:
  mongo:
    image: mongo:7.0
    container_name: lms_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=lms_assess
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./lms-backend
      dockerfile: Dockerfile
    container_name: lms_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/lms_assess
      - CLIENT_URL=http://localhost,http://localhost:80,http://localhost:5173
    depends_on:
      mongo:
        condition: service_healthy

  frontend:
    build:
      context: ./lms-frontend
      dockerfile: Dockerfile
    container_name: lms_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo-data:
